config/routes.rb
CfMusicgig::Application.routes.draw do

  resources :users, only: [:new, :create, :index]
  resources :sessions, only: [:create]
  resources :gigs
  resources :contacts, only: [:new, :create]

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/dashboard', to: 'dashboard#gig'
  get '/about', to: 'welcome#about'

  root 'welcome#index'

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname, :captcha => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "acrortest@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/gig.rb
class Gig < ActiveRecord::Base
  belongs_to :user
  image_accessor :cover_image
  validates :title, :description, :date, presence: true
  validates :title, :description, length: { minimum: 5}
  validates :title, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :gigs, dependent: :delete_all
  has_secure_password

  validates :email, uniqueness: true

  def email=(value)
    value = value.strip.downcase
    write_attribute :email, value
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :current_user?

  private

  def user_logged_in!
    return if current_user.present?
    flash[:alert] = "Please sign in to view that resource!"
    redirect_to login_url
  end

  def sign_in(user)
    session[:user_id] = user.id if user.present?
  end

    def sign_out
    session[:user_id] = nil
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id] if session[:user_id]
  end

  def current_user?
    current_user.present?
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      # flash.now[:error] = nil
      flash.now[:notice] = 'Your message has been sent!'
    else
      flash.now[:error] = 'Sorry, this message was not delivered. Please retry.'
      render :new
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :user_logged_in!

  def index
  end

  def gig
    # @gigs = Gig.all
    # @gigs = Gig.page(params[:page]).per(5)
    @gigs = Gig.order(:date).page(params[:page]).per(5)
  end
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  before_action :user_logged_in!

  def index
  end

  def new
    @gig = Gig.new
  end

  def create
    @gig = Gig.new(gig_params)
    @gig.user = current_user

    if @gig.save
      flash[:notice] = "Your gig has been added!"
      # redirect_to dashboard_path
      respond_to do |format|
        format.html { redirect_to @gig }
        format.js
      end
      # redirect_to @gig
    else
      render "new"
    end
  end

  def show
    @gig = Gig.find(params[:id])
  end

  def edit
    @gig = Gig.find(params[:id])
  end

  def update
    @gig = Gig.find(params[:id])
    if @gig.update(gig_params)
      flash[:notice] = "This gig has been updated."
      redirect_to gig_url
    else
      render "edit"
    end
  end

  def destroy
    @gig = Gig.find(params[:id])
    @gig.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_url }
      format.js
    end
    # redirect_to dashboard_url
  end

  private

  def gig_params
    params.require(:gig).permit(:title, :description, :cover_image, :retained_cover_image, :genre, :location, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by email: params[:email].downcase
    if user && user.authenticate(params[:password])
      # sign in
      session[:user_id] = user.id
      flash[:notice] = "You are signed in!"
      redirect_to root_url
    else
      flash.now[:alert] = "Invalid email/password."
      render "new"
    end
  end

  def destroy
    sign_out
    #session[:user_id] = nil
    flash[:notice] = "You are now signed out!"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_logged_in!, only: [:index]

  def index
    @gigs = current_user.gigs.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "You are now a user!"
      #session[:user_id] = @user.id
      sign_in @user
      redirect_to root_url
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1>Thank you for your message.</h1>
<p>We'll get back to you soon.</p>

app/views/contacts/new.html.erb
<h1>Contact</h1>

<div class="row">
  <div class="col-lg-6">
  <%= simple_form_for @contact, :html => {:class => "form-group"} do |f| %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :message, class: "form-control", rows: "10" %>
    </div>
    <div class="form-group">
      <%= f.hidden_field :nickname, :hint => "Leave this field blank!" %>
    </div>
    <%= f.submit "Send Message", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/dashboard/gig.html.erb
<h1>Gig Dashboard</h1>

<div class="container">
  <div class="row">
    <div class="col-lg-10">
      <p>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Gig Image</th>
              <th>Gig Title</th>
              <th>Description</th>
              <th>Location</th>
              <th>Event Date</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @gigs.each do |gig| %>
              <tr>
                <td><%= image_tag gig.cover_image.thumb("100x100").url if gig.cover_image_uid %></td>
                <td><%= link_to gig.title, gig %></td>
                <td><%= truncate(gig.description, length: 50) %></td>
                <td><%= gig.location %></td>
                <td><%= gig.date.strftime("%b %d %Y") rescue "Unfilled" %></td>
                <td class="btn btn-default"><%= link_to "View details", gig %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

      <ul class="pagination"><%= paginate @gigs %></ul>
      </p>
      <p class="btn btn-default"><%= link_to "New Gig", new_gig_path, id: "new_link", remote: true %></p>
    </div>
  </div>
</div> <!-- /container -->

app/views/gigs/_form.html.erb
<div class="row">
  <div class="col-lg-6">
  <%= form_for @gig, :html => {:multipart => true, :class => "form-group"} do |f| %>

    <% if @gig.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h3><%= pluralize(@gig.errors.count, "error") %>
          prohibited this gig from being saved:</h3>
        <ul>
        <% @gig.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control", rows: "10" %>
    </div>
    <div class="form-group">
      <%= f.label :location %>
      <%= f.select :location, [["Seattle", "Seattle"], ["New York", "New York"], ["Los Angeles", "Los Angeles"], ["Chicago", "Chicago"]], class: "form-control input-lg" %>
    </div>
    <div class="form-group">
      <%= f.label :genre %>
      <%= f.select :genre, [["Rock", "Rock"], ["Pop", "Rock"], ["Jazz", "Jazz"], ["Alternative", "Alternative"], ["R&B", "R&B"]], class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Event Date" %>
      <%= f.date_field :date, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.file_field :cover_image, class: "btn-file" %>
      <%= f.hidden_field :retained_cover_image %>
    </div>
    <%= f.submit class: "btn btn-primary" %>
  <% end %><br>

  <p class="btn btn-default"><%= link_to "Back To Dashboard", dashboard_path %></p>
  </div>
</div>

app/views/gigs/create.js.erb
$('#new_gig').remove();

app/views/gigs/destroy.js.erb
$('#edit_gig_<%= @gig.id %>').remove();

app/views/gigs/edit.html.erb
<h1>Edit Gig</h1>

<%= render "form" %>

app/views/gigs/new.html.erb
<h1>Create a new gig</h1>

<%= form_for @gig do |f| %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <%= f.submit %>
<% end %><br>

<%= link_to "Home", root_path %>

app/views/gigs/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>')

app/views/gigs/show.html.erb
<h1><%= @gig.title %></h1>

<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <dl>
        <dt>Description:</dt>
        <dd><%= @gig.description %></dd><br>
        <dt>Location:</dt>
        <dd><%= @gig.location %></dd><br>
        <dt>Genre:</dt>
        <dd><%= @gig.genre %></dd><br>
        <dt>Event Date:</dt>
        <dd><%= @gig.date.strftime("%b %d %Y") rescue "Unfilled" %></dd><br>
        <dd><%= image_tag @gig.cover_image.thumb("x300>").url if @gig.cover_image_uid %></dd>
        <% # image_tag @gig.cover_image.thumb("x300>").url if @gig.cover_image_uid, class: "thumbnail" %>
      </dl>
      <br>

      <p class="btn btn-default"><%= link_to "Back To Dashboard", dashboard_path %></p>
      <p class="btn btn-default"><%= link_to "New Gig", new_gig_path %></p>
      <% if current_user == @gig.user %>
        <p class="btn btn-default"><%= link_to "Edit Gig", edit_gig_path %></p>
        <p class="btn btn-default"><%= link_to "Delete Gig", @gig, method: :delete, confirm: "Are you sure you want to delete this gig?", remote: true %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicGig</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <nav class="navbar navbar-default" role="navigation">
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">MusicGig</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", new_contact_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dashboard <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Gigs", dashboard_path %></li>
                <li class="divider"></li>
                <li class="dropdown-header">Source Code</li>
                <li><a href="https://github.com/aries0420/cf-musicgig" target="_blank">GitHub</a></li>
                <li><a href="http://salty-savannah-6732.herokuapp.com" target="_blank">Heroku Deployment</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <div>
              <li class="navbar-text">
              <% if current_user.present? %>Welcome <%= link_to current_user.email, users_path %> | <%= link_to "Sign Out", logout_path %>
              <% else %>
                <%= link_to "Register", new_user_path %> | <%= link_to "Sign In", login_path %>
              <% end %>
              </li>
            </div>
          </ul>
        </div><!--/.navbar-collapse -->
      </div>
    </div>
  </nav>

  <% flash.each do |key, value| %>
    <div class="alert <%= key == :alert ? "alert-danger" : "alert-info" %>">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= value %>
    </div>
  <% end %>

  <%= yield %>
  <hr>

  <footer>
    <p>&copy; MusicGig 2013. All rights reserved.</p>
  </footer>
</div> <!-- /container -->

</body>
</html>

app/views/users/index.html.erb
<h1>My Account</h1>
<div class="container">
  <div class="row">
    <div class="col-lg-10">
      <% if current_user? %>
      <p class="text-primary">
        Name: <%= current_user.first_name %> <%= current_user.last_name %><br>
        Email: <%= current_user.email %>
      </p>
      <% end %>
    </div>
  </div>
</div>

<h3>My Gigs</h3>

<div class="container">
  <div class="row">
    <div class="col-lg-10">
      <% if current_user? %>
      <p>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Gig Title</th>
              <th>Description</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @gigs.each do |gig| %>
              <tr>
                <td><%= link_to gig.title, gig %></td>
                <td><%= truncate(gig.description, length: 50) %></td>
                <td class="btn btn-default"><%= link_to "Edit", edit_gig_path(gig) %></td>
                <td class="btn btn-default"><%= link_to "Delete", gig, method: :delete, confirm: "Are you sure you want to delete this gig?" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </p>
      <% end %>
      <p class="btn btn-default"><%= link_to "View All Gigs", dashboard_path %></p>
    </div>
  </div>
</div> <!-- /container -->

app/views/users/new.html.erb
<h1>New User Registration</h1>

<div class="row">
  <div class="col-lg-4">
  <%= form_for @user do |f| %>

    <% if @user.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h3><%= pluralize(@user.errors.count, "error") %>
          prohibited this user from being saved:</h3>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/welcome/about.html.erb
<div class="container">
  <h1>About</h1>
  <p>MusicGig is a platform that provides a medium for bookers, artists, and fans where gigs can be posted and searched for free. It empowers bookers and artists to efficiently take control of their gig hiring and self-promotion - Trustworthy, faster and secured.</p>
</div>

<div class="container">
  <h1>FAQ</h1>
  <p>

    <div class="panel-group" id="accordion">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Why MusicGig?</a>
          </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse in">
          <div class="panel-body">
            Because we're currently the only platform that helps musicians to better manage themselves that focuses in live music space.
          </div>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">Who are your target customers?</a>
          </h4>
        </div>
        <div id="collapseTwo" class="panel-collapse collapse">
          <div class="panel-body">
            Bookers (venues), artists (musicians), and fans (listeners).
          </div>
        </div>
      </div>

    </div>
  </p>
</div> <!-- /container -->

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>MusicGig Marketplace</h1>
    <p>A marketplace for bookers and artists to collaborate the match-making effort. Bookers can post gigs online for artists to apply. Ideally, it is also a platform for fans to come and vote for their favorite artists.</p>
    <p><a class="btn btn-primary btn-lg" href="/about">Learn more &raquo;</a></p>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <% if current_user? %>
      <h2>Current Users in the Marketplace</h2>
      <p>
        <ul>
          <% @users.each do |user| %>
            <li><%= user.email %></li>
          <% end %>
        </ul>
      </p>
      <% end %>
    </div>
  </div>
</div> <!-- /container -->